### ISSUE TITLE
error instalation

### ISSUE THREAD

**Issue by williambueno89** [falconsoft3d/pyerp#6]
with open('%s/installed_apps.py' % BASE_DIR, 'r') as ins_apps_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/teste/pyerp/installed_apps.py'

**Comment by fjsanzano** [comment]
Crea un fichero /installed_apps.py con el contenido de las aplicaciones que quieres instalar por ejemplo:
`apps.account`
`apps.sale`
Pero para la primera vez déjalo en blanco por que sino da error
